#version 450
/* Copyright (c) 2020-2024 Hans-Kristian Arntzen
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

// Originally written by Hans-Kristian Arntzen, and modified to use a different "ABI"

#extension GL_GOOGLE_include_directive : require

#include "bitextract.h"

// The shader will be dispatched with one invocation per pixel of the output image.
layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

// --- Push Constants ---
// We use push constants to pass image parameters efficiently.
layout(push_constant) uniform PushConstants {
    // Format of the source compressed data. We'll use Vulkan enum values.
    // VK_FORMAT_BC6H_UFLOAT_BLOCK = 143
    // VK_FORMAT_BC6H_SFLOAT_BLOCK = 144
    uint srcFormat;

    // The dimensions of the source compressed data buffer.
    uint srcRowLength;   // Stride in pixels of the source data
    uint srcImageHeight;

    // The destination image parameters.
    int offsetx;
    int offsety;
    uint dst_width;
    uint dst_height;

    uint srcBufferSize;

    uint unsupportedBitsBc; // bitmask
    uint watercoloredBitsBc;
    uint watermarkerSize;
} push_constants;

// --- Buffers ---
// Source buffer containing the compressed BC6 blocks.
// We read it as an array of 32-bit uints for easier bit manipulation.
layout(set = 0, binding = 0) readonly buffer SourceBuffer {
    uint data[];
} srcBuffer;

#ifdef USE_IMAGE_VIEW_OUTPUT
// Destination image view for the decompressed RGBA8 data.
// We use a storage image to write the decompressed pixels directly.
layout(set = 0, binding = 1, rgba16ui) uniform writeonly uimage2D dstImage;
#else
// Destination buffer for the decompressed RGBA8 data.
// We now use a raw storage buffer of uints.
layout(set = 0, binding = 1) writeonly buffer DestinationBuffer {
    uint data[];
} dstBuffer;
#endif

layout(std140, set = 0, binding = 2) uniform LUTs {
    int weight_table3[16];
    int weight_table4[16];

    int partition_table2[32];
    int anchor_table2[32];
} constants;

struct DecodedInterpolation
{
    ivec3 ep0, ep1;
    int weight;
};

ivec3 interpolate_endpoint(DecodedInterpolation interp)
{
    ivec3 rgb = ((64 - interp.weight) * interp.ep0 + interp.weight * interp.ep1 + 32) >> 6;
    return rgb;
}

ivec3 unquantize_endpoint(ivec3 ep, int bits, bool is_signed)
{
    ivec3 unq;
    if (is_signed)
    {
        ep = bitfieldExtract(ep, 0, bits);
        if (bits < 16)
        {
            ivec3 sgn = 1 - ((ep >> 30) & 2);
            ivec3 abs_ep = abs(ep);
            unq = ((abs_ep << 15) + 0x4000) >> (bits - 1);
            unq = mix(unq, ivec3(0), equal(ep, ivec3(0)));
            unq = mix(unq, ivec3(0x7fff), greaterThanEqual(abs_ep, ivec3((1 << (bits - 1)) - 1)));
            unq *= sgn;
        }
        else
            unq = ep;
    }
    else
    {
        ep = ivec3(bitfieldExtract(uvec3(ep), 0, bits));
        if (bits < 15)
        {
            unq = ((ep << 15) + 0x4000) >> (bits - 1);
            unq = mix(unq, ivec3(0), equal(ep, ivec3(0)));
            unq = mix(unq, ivec3(0xffff), equal(ep, ivec3((1 << bits) - 1)));
        }
        else
            unq = ep;
    }
    return unq;
}

DecodedInterpolation decode_bc6_mode0(uvec4 payload, int linear_pixel, int part, int anchor_pixel, bool is_signed)
{
    ivec3 ep0, ep1;

    int r0 = extract_bits(payload, 5, 10);
    int g0 = extract_bits(payload, 15, 10);
    int b0 = extract_bits(payload, 25, 10);
    ep0 = ivec3(r0, g0, b0);

    if (part != 0)
    {
        int r2 = extract_bits_sign(payload, 65, 5);
        int g2 = extract_bits(payload, 41, 4) | (extract_bits_sign(payload, 2, 1) << 4);
        int b2 = extract_bits(payload, 61, 4) | (extract_bits_sign(payload, 3, 1) << 4);

        int r3 = extract_bits_sign(payload, 71, 5);
        int g3 = extract_bits(payload, 51, 4) | (extract_bits_sign(payload, 40, 1) << 4);
        int b3 = extract_bits(payload, 50, 1) | (extract_bits(payload, 60, 1) << 1) | (extract_bits(payload, 70, 1) << 2) |
                (extract_bits(payload, 76, 1) << 3) | (extract_bits_sign(payload, 4, 1) << 4);

        ep1 = ivec3(r3, g3, b3) + ep0;
        ep0 += ivec3(r2, g2, b2);
    }
    else
    {
        int r1 = extract_bits_sign(payload, 35, 5);
        int g1 = extract_bits_sign(payload, 45, 5);
        int b1 = extract_bits_sign(payload, 55, 5);
        ep1 = ivec3(r1, g1, b1) + ep0;
    }

    ep0 = unquantize_endpoint(ep0, 10, is_signed);
    ep1 = unquantize_endpoint(ep1, 10, is_signed);

    int index = extract_bits(
        payload,
        max(81 + linear_pixel * 3 - int(linear_pixel > anchor_pixel), 82),
        (linear_pixel == 0 || linear_pixel == anchor_pixel) ? 2 : 3);

    int w = constants.weight_table3[index];
    return DecodedInterpolation(ep0, ep1, w);
}

DecodedInterpolation decode_bc6_mode1(uvec4 payload, int linear_pixel, int part, int anchor_pixel, bool is_signed)
{
    ivec3 ep0, ep1;

    int r0 = extract_bits(payload, 5, 7);
    int g0 = extract_bits(payload, 15, 7);
    int b0 = extract_bits(payload, 25, 7);
    ep0 = ivec3(r0, g0, b0);

    if (part != 0)
    {
        int r2 = extract_bits_sign(payload, 65, 6);
        int g2 = extract_bits(payload, 41, 4) | (extract_bits(payload, 24, 1) << 4) | (extract_bits_sign(payload, 2, 1) << 5);
        int b2 = extract_bits(payload, 61, 4) | (extract_bits(payload, 14, 1) << 4) | (extract_bits_sign(payload, 22, 1) << 5);

        int r3 = extract_bits_sign(payload, 71, 6);
        int g3 = extract_bits(payload, 51, 4) | (extract_bits_sign(payload, 3, 2) << 4);
        int b3 = extract_bits(payload, 12, 2) | (extract_bits(payload, 23, 1) << 2) | (extract_bits(payload, 32, 1) << 3) |
                (extract_bits(payload, 34, 1) << 4) | (extract_bits_sign(payload, 33, 1) << 5);

        ep1 = ivec3(r3, g3, b3) + ep0;
        ep0 += ivec3(r2, g2, b2);
    }
    else
    {
        int r1 = extract_bits_sign(payload, 35, 6);
        int g1 = extract_bits_sign(payload, 45, 6);
        int b1 = extract_bits_sign(payload, 55, 6);
        ep1 = ivec3(r1, g1, b1) + ep0;
    }

    ep0 = unquantize_endpoint(ep0, 7, is_signed);
    ep1 = unquantize_endpoint(ep1, 7, is_signed);

    int index = extract_bits(
        payload,
        max(81 + linear_pixel * 3 - int(linear_pixel > anchor_pixel), 82),
        (linear_pixel == 0 || linear_pixel == anchor_pixel) ? 2 : 3);

    int w = constants.weight_table3[index];
    return DecodedInterpolation(ep0, ep1, w);
}

DecodedInterpolation decode_bc6_mode2(uvec4 payload, int linear_pixel, int part, int anchor_pixel, bool is_signed)
{
    ivec3 ep0, ep1;

    int r0 = extract_bits(payload, 5, 10) | (extract_bits(payload, 40, 1) << 10);
    int g0 = extract_bits(payload, 15, 10) | (extract_bits(payload, 49, 1) << 10);
    int b0 = extract_bits(payload, 25, 10) | (extract_bits(payload, 59, 1) << 10);
    ep0 = ivec3(r0, g0, b0);

    if (part != 0)
    {
        int r2 = extract_bits_sign(payload, 65, 5);
        int g2 = extract_bits_sign(payload, 41, 4);
        int b2 = extract_bits_sign(payload, 61, 4);

        int r3 = extract_bits_sign(payload, 71, 5);
        int g3 = extract_bits_sign(payload, 51, 4);
        int b3 = extract_bits(payload, 50, 1) | (extract_bits(payload, 60, 1) << 1) |
                (extract_bits(payload, 70, 1) << 2) | (extract_bits_sign(payload, 76, 1) << 3);

        ep1 = ivec3(r3, g3, b3) + ep0;
        ep0 += ivec3(r2, g2, b2);
    }
    else
    {
        int r1 = extract_bits_sign(payload, 35, 5);
        int g1 = extract_bits_sign(payload, 45, 4);
        int b1 = extract_bits_sign(payload, 55, 4);
        ep1 = ivec3(r1, g1, b1) + ep0;
    }

    ep0 = unquantize_endpoint(ep0, 11, is_signed);
    ep1 = unquantize_endpoint(ep1, 11, is_signed);

    int index = extract_bits(
        payload,
        max(81 + linear_pixel * 3 - int(linear_pixel > anchor_pixel), 82),
        (linear_pixel == 0 || linear_pixel == anchor_pixel) ? 2 : 3);

    int w = constants.weight_table3[index];
    return DecodedInterpolation(ep0, ep1, w);
}

DecodedInterpolation decode_bc6_mode3(uvec4 payload, int linear_pixel, bool is_signed)
{
    int r0 = extract_bits(payload, 5, 10);
    int g0 = extract_bits(payload, 15, 10);
    int b0 = extract_bits(payload, 25, 10);
    int r1 = extract_bits(payload, 35, 10);
    int g1 = extract_bits(payload, 45, 10);
    int b1 = extract_bits(payload, 55, 10);

    ivec3 ep0 = ivec3(r0, g0, b0);
    ivec3 ep1 = ivec3(r1, g1, b1);
    ep0 = unquantize_endpoint(ep0, 10, is_signed);
    ep1 = unquantize_endpoint(ep1, 10, is_signed);

    int index = extract_bits(
        payload,
        max(64 + linear_pixel * 4, 65),
        linear_pixel == 0 ? 3 : 4);

    int w = constants.weight_table4[index];
    return DecodedInterpolation(ep0, ep1, w);
}

DecodedInterpolation decode_bc6_mode6(uvec4 payload, int linear_pixel, int part, int anchor_pixel, bool is_signed)
{
    ivec3 ep0, ep1;

    int r0 = extract_bits(payload, 5, 10) | (extract_bits(payload, 39, 1) << 10);
    int g0 = extract_bits(payload, 15, 10) | (extract_bits(payload, 50, 1) << 10);
    int b0 = extract_bits(payload, 25, 10) | (extract_bits(payload, 59, 1) << 10);
    ep0 = ivec3(r0, g0, b0);

    if (part != 0)
    {
        int r2 = extract_bits_sign(payload, 65, 4);
        int g2 = extract_bits(payload, 41, 4) | (extract_bits_sign(payload, 75, 1) << 4);
        int b2 = extract_bits_sign(payload, 61, 4);

        int r3 = extract_bits_sign(payload, 71, 4);
        int g3 = extract_bits(payload, 51, 4) | (extract_bits_sign(payload, 40, 1) << 4);
        int b3 = extract_bits(payload, 69, 1) | (extract_bits(payload, 60, 1) << 1) |
                (extract_bits(payload, 70, 1) << 2) | (extract_bits_sign(payload, 76, 1) << 3);

        ep1 = ivec3(r3, g3, b3) + ep0;
        ep0 += ivec3(r2, g2, b2);
    }
    else
    {
        int r1 = extract_bits_sign(payload, 35, 4);
        int g1 = extract_bits_sign(payload, 45, 5);
        int b1 = extract_bits_sign(payload, 55, 4);
        ep1 = ivec3(r1, g1, b1) + ep0;
    }

    ep0 = unquantize_endpoint(ep0, 11, is_signed);
    ep1 = unquantize_endpoint(ep1, 11, is_signed);

    int index = extract_bits(
        payload,
        max(81 + linear_pixel * 3 - int(linear_pixel > anchor_pixel), 82),
        (linear_pixel == 0 || linear_pixel == anchor_pixel) ? 2 : 3);

    int w = constants.weight_table3[index];
    return DecodedInterpolation(ep0, ep1, w);
}

DecodedInterpolation decode_bc6_mode7(uvec4 payload, int linear_pixel, bool is_signed)
{
    int r0 = extract_bits(payload, 5, 10) | (extract_bits(payload, 44, 1) << 10);
    int g0 = extract_bits(payload, 15, 10) | (extract_bits(payload, 54, 1) << 10);
    int b0 = extract_bits(payload, 25, 10) | (extract_bits(payload, 64, 1) << 10);

    int r1 = extract_bits_sign(payload, 35, 9);
    int g1 = extract_bits_sign(payload, 45, 9);
    int b1 = extract_bits_sign(payload, 55, 9);

    r1 += r0;
    g1 += g0;
    b1 += b0;

    ivec3 ep0 = ivec3(r0, g0, b0);
    ivec3 ep1 = ivec3(r1, g1, b1);
    ep0 = unquantize_endpoint(ep0, 11, is_signed);
    ep1 = unquantize_endpoint(ep1, 11, is_signed);

    int index = extract_bits(
        payload,
        max(64 + linear_pixel * 4, 65),
        linear_pixel == 0 ? 3 : 4);

    int w = constants.weight_table4[index];
    return DecodedInterpolation(ep0, ep1, w);
}

DecodedInterpolation decode_bc6_mode10(uvec4 payload, int linear_pixel, int part, int anchor_pixel, bool is_signed)
{
    ivec3 ep0, ep1;

    int r0 = extract_bits(payload, 5, 10) | (extract_bits(payload, 39, 1) << 10);
    int g0 = extract_bits(payload, 15, 10) | (extract_bits(payload, 49, 1) << 10);
    int b0 = extract_bits(payload, 25, 10) | (extract_bits(payload, 60, 1) << 10);
    ep0 = ivec3(r0, g0, b0);

    if (part != 0)
    {
        int r2 = extract_bits_sign(payload, 65, 4);
        int g2 = extract_bits_sign(payload, 41, 4);
        int b2 = extract_bits(payload, 61, 4) | (extract_bits_sign(payload, 40, 1) << 4);

        int r3 = extract_bits_sign(payload, 71, 4);
        int g3 = extract_bits_sign(payload, 51, 4);
        int b3 = extract_bits(payload, 50, 1) | (extract_bits(payload, 69, 2) << 1) |
                (extract_bits(payload, 76, 1) << 3) | (extract_bits_sign(payload, 75, 1) << 4);

        ep1 = ivec3(r3, g3, b3) + ep0;
        ep0 += ivec3(r2, g2, b2);
    }
    else
    {
        int r1 = extract_bits_sign(payload, 35, 4);
        int g1 = extract_bits_sign(payload, 45, 4);
        int b1 = extract_bits_sign(payload, 55, 5);
        ep1 = ivec3(r1, g1, b1) + ep0;
    }

    ep0 = unquantize_endpoint(ep0, 11, is_signed);
    ep1 = unquantize_endpoint(ep1, 11, is_signed);

    int index = extract_bits(
        payload,
        max(81 + linear_pixel * 3 - int(linear_pixel > anchor_pixel), 82),
        (linear_pixel == 0 || linear_pixel == anchor_pixel) ? 2 : 3);

    int w = constants.weight_table3[index];
    return DecodedInterpolation(ep0, ep1, w);
}

DecodedInterpolation decode_bc6_mode11(uvec4 payload, int linear_pixel, bool is_signed)
{
    int r0 = extract_bits(payload, 5, 10) | (extract_bits_reverse(payload, 43, 2) << 10);
    int g0 = extract_bits(payload, 15, 10) | (extract_bits_reverse(payload, 53, 2) << 10);
    int b0 = extract_bits(payload, 25, 10) | (extract_bits_reverse(payload, 63, 2) << 10);

    int r1 = extract_bits_sign(payload, 35, 8);
    int g1 = extract_bits_sign(payload, 45, 8);
    int b1 = extract_bits_sign(payload, 55, 8);

    r1 += r0;
    g1 += g0;
    b1 += b0;

    ivec3 ep0 = ivec3(r0, g0, b0);
    ivec3 ep1 = ivec3(r1, g1, b1);
    ep0 = unquantize_endpoint(ep0, 12, is_signed);
    ep1 = unquantize_endpoint(ep1, 12, is_signed);

    int index = extract_bits(
        payload,
        max(64 + linear_pixel * 4, 65),
        linear_pixel == 0 ? 3 : 4);

    int w = constants.weight_table4[index];
    return DecodedInterpolation(ep0, ep1, w);
}

DecodedInterpolation decode_bc6_mode14(uvec4 payload, int linear_pixel, int part, int anchor_pixel, bool is_signed)
{
    ivec3 ep0, ep1;

    int r0 = extract_bits(payload, 5, 9);
    int g0 = extract_bits(payload, 15, 9);
    int b0 = extract_bits(payload, 25, 9);
    ep0 = ivec3(r0, g0, b0);

    if (part != 0)
    {
        int r2 = extract_bits_sign(payload, 65, 5);
        int g2 = extract_bits(payload, 41, 4) | (extract_bits_sign(payload, 24, 1) << 4);
        int b2 = extract_bits(payload, 61, 4) | (extract_bits_sign(payload, 14, 1) << 4);

        int r3 = extract_bits_sign(payload, 71, 5);
        int g3 = extract_bits(payload, 51, 4) | (extract_bits_sign(payload, 40, 1) << 4);
        int b3 = extract_bits(payload, 50, 1) | (extract_bits(payload, 60, 1) << 1) |
                (extract_bits(payload, 70, 1) << 2) |
                (extract_bits(payload, 76, 1) << 3) | (extract_bits_sign(payload, 34, 1) << 4);

        ep1 = ivec3(r3, g3, b3) + ep0;
        ep0 += ivec3(r2, g2, b2);
    }
    else
    {
        int r1 = extract_bits_sign(payload, 35, 5);
        int g1 = extract_bits_sign(payload, 45, 5);
        int b1 = extract_bits_sign(payload, 55, 5);
        ep1 = ivec3(r1, g1, b1) + ep0;
    }

    ep0 = unquantize_endpoint(ep0, 9, is_signed);
    ep1 = unquantize_endpoint(ep1, 9, is_signed);

    int index = extract_bits(
        payload,
        max(81 + linear_pixel * 3 - int(linear_pixel > anchor_pixel), 82),
        (linear_pixel == 0 || linear_pixel == anchor_pixel) ? 2 : 3);

    int w = constants.weight_table3[index];
    return DecodedInterpolation(ep0, ep1, w);
}

DecodedInterpolation decode_bc6_mode15(uvec4 payload, int linear_pixel, bool is_signed)
{
    int r0 = extract_bits(payload, 5, 10) | (extract_bits_reverse(payload, 39, 6) << 10);
    int g0 = extract_bits(payload, 15, 10) | (extract_bits_reverse(payload, 49, 6) << 10);
    int b0 = extract_bits(payload, 25, 10) | (extract_bits_reverse(payload, 59, 6) << 10);

    int r1 = extract_bits_sign(payload, 35, 4);
    int g1 = extract_bits_sign(payload, 45, 4);
    int b1 = extract_bits_sign(payload, 55, 4);

    r1 += r0;
    g1 += g0;
    b1 += b0;

    ivec3 ep0 = ivec3(r0, g0, b0);
    ivec3 ep1 = ivec3(r1, g1, b1);
    ep0 = unquantize_endpoint(ep0, 16, is_signed);
    ep1 = unquantize_endpoint(ep1, 16, is_signed);

    int index = extract_bits(
        payload,
        max(64 + linear_pixel * 4, 65),
        linear_pixel == 0 ? 3 : 4);

    int w = constants.weight_table4[index];
    return DecodedInterpolation(ep0, ep1, w);
}

DecodedInterpolation decode_bc6_mode18(uvec4 payload, int linear_pixel, int part, int anchor_pixel, bool is_signed)
{
    ivec3 ep0, ep1;

    int r0 = extract_bits(payload, 5, 8);
    int g0 = extract_bits(payload, 15, 8);
    int b0 = extract_bits(payload, 25, 8);
    ep0 = ivec3(r0, g0, b0);

    if (part != 0)
    {
        int r2 = extract_bits_sign(payload, 65, 6);
        int g2 = extract_bits(payload, 41, 4) | (extract_bits_sign(payload, 24, 1) << 4);
        int b2 = extract_bits(payload, 61, 4) | (extract_bits_sign(payload, 14, 1) << 4);

        int r3 = extract_bits_sign(payload, 71, 6);
        int g3 = extract_bits(payload, 51, 4) | (extract_bits_sign(payload, 13, 1) << 4);
        int b3 = extract_bits(payload, 50, 1) | (extract_bits(payload, 60, 1) << 1) |
                (extract_bits(payload, 23, 1) << 2) | (extract_bits_sign(payload, 33, 2) << 3);

        ep1 = ivec3(r3, g3, b3) + ep0;
        ep0 += ivec3(r2, g2, b2);
    }
    else
    {
        int r1 = extract_bits_sign(payload, 35, 6);
        int g1 = extract_bits_sign(payload, 45, 5);
        int b1 = extract_bits_sign(payload, 55, 5);
        ep1 = ivec3(r1, g1, b1) + ep0;
    }

    ep0 = unquantize_endpoint(ep0, 8, is_signed);
    ep1 = unquantize_endpoint(ep1, 8, is_signed);

    int index = extract_bits(
        payload,
        max(81 + linear_pixel * 3 - int(linear_pixel > anchor_pixel), 82),
        (linear_pixel == 0 || linear_pixel == anchor_pixel) ? 2 : 3);

    int w = constants.weight_table3[index];
    return DecodedInterpolation(ep0, ep1, w);
}

DecodedInterpolation decode_bc6_mode22(uvec4 payload, int linear_pixel, int part, int anchor_pixel, bool is_signed)
{
    ivec3 ep0, ep1;

    int r0 = extract_bits(payload, 5, 8);
    int g0 = extract_bits(payload, 15, 8);
    int b0 = extract_bits(payload, 25, 8);
    ep0 = ivec3(r0, g0, b0);

    if (part != 0)
    {
        int r2 = extract_bits_sign(payload, 65, 5);
        int g2 = extract_bits(payload, 41, 4) | (extract_bits(payload, 24, 1) << 4) | (extract_bits_sign(payload, 23, 1) << 5);
        int b2 = extract_bits(payload, 61, 4) | (extract_bits_sign(payload, 14, 1) << 4);

        int r3 = extract_bits_sign(payload, 71, 5);
        int g3 = extract_bits(payload, 51, 4) | (extract_bits(payload, 40, 1) << 4) | (extract_bits_sign(payload, 33, 1) << 5);
        int b3 = extract_bits(payload, 13, 1) | (extract_bits(payload, 60, 1) << 1) |
                (extract_bits(payload, 70, 1) << 2) | (extract_bits(payload, 76, 1) << 3) |
                (extract_bits_sign(payload, 34, 1) << 4);

        ep1 = ivec3(r3, g3, b3) + ep0;
        ep0 += ivec3(r2, g2, b2);
    }
    else
    {
        int r1 = extract_bits_sign(payload, 35, 5);
        int g1 = extract_bits_sign(payload, 45, 6);
        int b1 = extract_bits_sign(payload, 55, 5);
        ep1 = ivec3(r1, g1, b1) + ep0;
    }

    ep0 = unquantize_endpoint(ep0, 8, is_signed);
    ep1 = unquantize_endpoint(ep1, 8, is_signed);

    int index = extract_bits(
        payload,
        max(81 + linear_pixel * 3 - int(linear_pixel > anchor_pixel), 82),
        (linear_pixel == 0 || linear_pixel == anchor_pixel) ? 2 : 3);

    int w = constants.weight_table3[index];
    return DecodedInterpolation(ep0, ep1, w);
}

DecodedInterpolation decode_bc6_mode26(uvec4 payload, int linear_pixel, int part, int anchor_pixel, bool is_signed)
{
    ivec3 ep0, ep1;

    int r0 = extract_bits(payload, 5, 8);
    int g0 = extract_bits(payload, 15, 8);
    int b0 = extract_bits(payload, 25, 8);
    ep0 = ivec3(r0, g0, b0);

    if (part != 0)
    {
        int r2 = extract_bits_sign(payload, 65, 5);
        int g2 = extract_bits(payload, 41, 4) | (extract_bits_sign(payload, 24, 1) << 4);
        int b2 = extract_bits(payload, 61, 4) | (extract_bits(payload, 14, 1) << 4) | (extract_bits_sign(payload, 23, 1) << 5);

        int r3 = extract_bits_sign(payload, 71, 5);
        int g3 = extract_bits(payload, 51, 4) | (extract_bits_sign(payload, 40, 1) << 4);
        int b3 = extract_bits(payload, 50, 1) | (extract_bits(payload, 13, 1) << 1) |
                (extract_bits(payload, 70, 1) << 2) | (extract_bits(payload, 76, 1) << 3) |
                (extract_bits(payload, 34, 1) << 4) | (extract_bits_sign(payload, 33, 1) << 5);

        ep1 = ivec3(r3, g3, b3) + ep0;
        ep0 += ivec3(r2, g2, b2);
    }
    else
    {
        int r1 = extract_bits_sign(payload, 35, 5);
        int g1 = extract_bits_sign(payload, 45, 5);
        int b1 = extract_bits_sign(payload, 55, 6);
        ep1 = ivec3(r1, g1, b1) + ep0;
    }

    ep0 = unquantize_endpoint(ep0, 8, is_signed);
    ep1 = unquantize_endpoint(ep1, 8, is_signed);

    int index = extract_bits(
        payload,
        max(81 + linear_pixel * 3 - int(linear_pixel > anchor_pixel), 82),
        (linear_pixel == 0 || linear_pixel == anchor_pixel) ? 2 : 3);

    int w = constants.weight_table3[index];
    return DecodedInterpolation(ep0, ep1, w);
}

DecodedInterpolation decode_bc6_mode30(uvec4 payload, int linear_pixel, int part, int anchor_pixel, bool is_signed)
{
    ivec3 ep0, ep1;

    if (part != 0)
    {
        int r2 = extract_bits(payload, 65, 6);
        int g2 = extract_bits(payload, 41, 4) | (extract_bits(payload, 24, 1) << 4) | (extract_bits(payload, 21, 1) << 5);
        int b2 = extract_bits(payload, 61, 4) | (extract_bits(payload, 14, 1) << 4) | (extract_bits(payload, 22, 1) << 5);

        int r3 = extract_bits(payload, 71, 6);
        int g3 = extract_bits(payload, 51, 4) | (extract_bits(payload, 11, 1) << 4) | (extract_bits(payload, 31, 1) << 5);
        int b3 = extract_bits(payload, 12, 2) | (extract_bits(payload, 23, 1) << 2) |
            (extract_bits(payload, 32, 1) << 3) | (extract_bits(payload, 34, 1) << 4) | (extract_bits(payload, 33, 1) << 5);

        ep0 = ivec3(r2, g2, b2);
        ep1 = ivec3(r3, g3, b3);
    }
    else
    {
        int r0 = extract_bits(payload, 5, 6);
        int g0 = extract_bits(payload, 15, 6);
        int b0 = extract_bits(payload, 25, 6);

        int r1 = extract_bits(payload, 35, 6);
        int g1 = extract_bits(payload, 45, 6);
        int b1 = extract_bits(payload, 55, 6);

        ep0 = ivec3(r0, g0, b0);
        ep1 = ivec3(r1, g1, b1);
    }

    ep0 = unquantize_endpoint(ep0, 6, is_signed);
    ep1 = unquantize_endpoint(ep1, 6, is_signed);

    int index = extract_bits(
        payload,
        max(81 + linear_pixel * 3 - int(linear_pixel > anchor_pixel), 82),
        (linear_pixel == 0 || linear_pixel == anchor_pixel) ? 2 : 3);

    int w = constants.weight_table3[index];
    return DecodedInterpolation(ep0, ep1, w);
}

// --- Shared Memory for Optimization ---
shared uvec4 shared_block_data[4]; // One 128-bit block for each 4x4 quad-group in the 8x8 workgroup.

// --- Main Decode Function ---
void main() {
    // Calculate pixel coordinate from workgroup and local invocation IDs
    ivec2 coord = ivec2(gl_WorkGroupID.xy) * 8 + ivec2(gl_LocalInvocationID.xy);
    ivec2 final_dst_coord = ivec2(push_constants.offsetx, push_constants.offsety) + coord;

    // Check if this invocation is out of bounds for the destination image
    if (coord.x >= push_constants.dst_width || coord.y >= push_constants.dst_height) {
        return;
    }

    // Check the bitmask
    bool is_masked = (push_constants.unsupportedBitsBc & (1 << (push_constants.srcFormat - 131))) != 0;
    bool is_watermarked = ((push_constants.watercoloredBitsBc & (1 << (push_constants.srcFormat - 131))) != 0)
        && coord.x < push_constants.watermarkerSize && coord.y < push_constants.watermarkerSize;
    if (is_masked || is_watermarked) {
#define RETURN(r,g,b) imageStore(dstImage, final_dst_coord, ivec4(r, g, b, 0x3c00)); break
#ifdef USE_IMAGE_VIEW_OUTPUT
        switch (push_constants.srcFormat) {
        case 143:
            RETURN(0x3c00, 0x3c00, 0); // Magenta
        case 144:
            RETURN(0x3c00, 0, 0); // Red
        default:
            RETURN(0xff, 0xff, 0xff); // White
        }
#endif
        return;
    }

    // Calculate the block coordinate
    uint block_stride = (push_constants.srcRowLength + 3) / 4;
    uint local_thread_id = gl_LocalInvocationID.y * 8 + gl_LocalInvocationID.x;
    if (local_thread_id < 4) {
        // Calculate source block coordinates on the 2x2 = 4 grid
        uvec2 local_block_coord = uvec2(local_thread_id % 2, local_thread_id / 2);
        uvec2 src_block_coord = uvec2(gl_WorkGroupID.xy) * 2 + local_block_coord;
        
        // Check if source block is within compressed texture bounds
        // Each block is a 4x4 patch of texels
        uint src_blocks_width = (push_constants.dst_width + 3) / 4;   // Blocks, not pixels
        uint src_blocks_height = (push_constants.dst_height + 3) / 4;
        if (src_block_coord.x < src_blocks_width && src_block_coord.y < src_blocks_height) {
            uint src_block_index = uint(src_block_coord.y) * block_stride + uint(src_block_coord.x);
            uint data_offset = src_block_index * 4;
            uint data0 = srcBuffer.data[data_offset];
            uint data1 = srcBuffer.data[data_offset + 1];
            uint data2 = srcBuffer.data[data_offset + 2];
            uint data3 = srcBuffer.data[data_offset + 3];
            shared_block_data[local_thread_id] = uvec4(data0, data1, data2, data3);
        } else {
            shared_block_data[local_thread_id] = uvec4(0);
        }
    }

    // Synchronize to ensure all loaders have written their data before any invocation reads it
    barrier();
    
    uvec2 block_coord = gl_LocalInvocationID.xy / 4;
    uint block_index = block_coord.y * 2 + block_coord.x;
    uvec4 payload = shared_block_data[block_index];

    // Decode the local pixel this thread is responsible in the 4x4 grid
    ivec2 tile_coord = coord % 4;
    int linear_pixel = 4 * tile_coord.y + tile_coord.x;

    DecodedInterpolation interp;

    bool is_signed = (push_constants.srcFormat == 144); // VK_FORMAT_BC6H_SFLOAT_BLOCK

    int mode = extract_bits(payload, 0, 5);
    int part_index = extract_bits(payload, 77, 5);
    int part = (constants.partition_table2[part_index] >> linear_pixel) & 1;
    int anchor_pixel = constants.anchor_table2[part_index];

    // The switch statement is the same, but now passes `is_signed` to the decode functions.
    if ((mode & 2) == 0) {
        if ((mode & 1) != 0)
            interp = decode_bc6_mode1(payload, linear_pixel, part, anchor_pixel, is_signed);
        else
            interp = decode_bc6_mode0(payload, linear_pixel, part, anchor_pixel, is_signed);
    } else {
        switch (mode) {
        case 2: interp = decode_bc6_mode2(payload, linear_pixel, part, anchor_pixel, is_signed); break;
        case 3: interp = decode_bc6_mode3(payload, linear_pixel, is_signed); break;
        case 6: interp = decode_bc6_mode6(payload, linear_pixel, part, anchor_pixel, is_signed); break;
        case 7: interp = decode_bc6_mode7(payload, linear_pixel, is_signed); break;
        case 10: interp = decode_bc6_mode10(payload, linear_pixel, part, anchor_pixel, is_signed); break;
        case 11: interp = decode_bc6_mode11(payload, linear_pixel, is_signed); break;
        case 14: interp = decode_bc6_mode14(payload, linear_pixel, part, anchor_pixel, is_signed); break;
        case 15: interp = decode_bc6_mode15(payload, linear_pixel, is_signed); break;
        case 18: interp = decode_bc6_mode18(payload, linear_pixel, part, anchor_pixel, is_signed); break;
        case 22: interp = decode_bc6_mode22(payload, linear_pixel, part, anchor_pixel, is_signed); break;
        case 26: interp = decode_bc6_mode26(payload, linear_pixel, part, anchor_pixel, is_signed); break;
        case 30: interp = decode_bc6_mode30(payload, linear_pixel, part, anchor_pixel, is_signed); break;
        default: interp = DecodedInterpolation(ivec3(0x3c00, 0, 0x3c00), ivec3(0x3c00, 0, 0x3c00), 0); break;
        }
    }

    ivec3 rgb_result = interpolate_endpoint(interp);
    if (is_signed)
    {
        ivec3 neg_result = 0x8000 | (((-rgb_result) * 31) >> 5);
        ivec3 pos_result = (rgb_result * 31) >> 5;
        rgb_result = mix(pos_result, neg_result, lessThan(rgb_result, ivec3(0)));

        // Fixup for -0.0. Seems to not be emitted by hardware decoder.
        rgb_result = mix(rgb_result, ivec3(0), equal(rgb_result, ivec3(0x8000)));
    } else {
        rgb_result = (rgb_result * 31) >> 6;
    }

#ifdef USE_IMAGE_VIEW_OUTPUT
    uvec4 final_rbga_color = uvec4(rgb_result, 0x3c00); // Alpha is always 1.0 for BC6.
    imageStore(dstImage, final_dst_coord, final_rbga_color);
#else
    // Calculate the linear index into the destination buffer using its row length (dst_width is the stride)
    int dst_index = int(coord.y * push_constants.dst_width + coord.x);
    // Pack into halfp 16b format
    uint packed_rg = (uint(rgb_result.r) & 0xFFFFu) | 
                 ((uint(rgb_result.g) & 0xFFFFu) << 16);
    uint packed_ba = (uint(rgb_result.b) & 0xFFFFu) | 
                    (0x3C00u << 16); // 0x3C00 is half-precision 1.0
    dstBuffer.data[dst_index * 2] =  packed_rg;
    dstBuffer.data[dst_index * 2 + 1] =  packed_ba;
#endif
}
