## Copyright © 2024 The Mesa3D Authors
## SPDX-License-Identifier: MIT

## DO NOT EDIT - This file is automatically generated by vk_unwrapper_gen.py

#ifndef VK_PRINTER_H
#define VK_PRINTER_H

#include <sys/time.h>
#include "vulkan/util/vk_alloc.h"
#include "wrapper_private.h"
#include "wrapper_log.h"

#ifdef __cplusplus
extern "C" {
#endif

## static FILE* __vk_print_fd;
## static int64_t __vk_start_ms;

% for s in all_vk_types:
% if s.name not in blacklisted_vk_types or s.name == 'VkShaderModuleCreateInfo':
void vk_print_${s.name}(int can_log_level, int log_level, FILE*, const char* prefix, const ${s.name} *in_info);
#define VK_PRINT_${s.name}(prefix, in_info) vk_print_${s.name}(VK_CMD_CAN_LOG_LEVEL, VK_CMD_ALL, VK_CMD_FD, prefix, in_info)
#define VK_LOG_${s.name}(prefix, obj) if (should_log() >= LOG_LEVEL_DEBUG) { \
   FILE* log_fd = LOG_FD; \
   vk_print_${s.name}(should_log(), LOG_LEVEL_DEBUG, log_fd, prefix, obj); \
   fflush(log_fd); \
}
% endif
% endfor

#ifdef __cplusplus
}
#endif

#endif /* VK_PRINTER_H */