// Copyright © 2025 Lee Gao
// SPDX-License-Identifier: MIT

// DO NOT EDIT - This file is automatically generated by vk_unwrapper_gen.py

#include "vk_printers.h"

#include "spirv_edit.h"
#include "vulkan/runtime/vk_log.h"
#include "vulkan/util/vk_util.h"

/*
${all_vk_types}
*/

#define PRINTER_EXTRAS_VkShaderModuleCreateInfo VK_CMD_FLUSH(); print_spirv_code(next_prefix, in_info);

static void print_spirv_code(const char* prefix, const VkShaderModuleCreateInfo *in_info) {
    int size = in_info->codeSize;
    const uint32_t* pCode = in_info->pCode;
    if (size == 0 || !pCode) {
        return;
    }
    // Print the SPIR-V code in int32 hex with 32 bytes (8 uint32_t) per line
    int i = 0;
    while (i < size / 4) {
        if (i + 7 < size / 4) {
            VK_CMD_PRINTF("%s.spirv(%p)[%04x]: %08x %08x %08x %08x %08x %08x %08x %08x\n", prefix, pCode, 4 * i, 
                          pCode[i], pCode[i + 1], pCode[i + 2], pCode[i + 3], 
                          pCode[i + 4], pCode[i + 5], pCode[i + 6], pCode[i + 7]);
            i += 8;
            continue;
        }

        if (i % 8 == 0) {
            VK_CMD_PRINTF("%s.spirv(%p)[%04x]: ", prefix, pCode, 4 * i);
        }
        VK_CMD_PRINTF("%08x ", pCode[i]);
        i++;
    }
    VK_CMD_PRINTF("\n\n");
    log_disassembly_to_cmd_log(pCode, size / 4);
    VK_CMD_FLUSH();
}

% for s in sorted(all_vk_types, key=lambda s: s.name):
% if s.name not in blacklisted_vk_types or s.name == 'VkShaderModuleCreateInfo':

void
vk_print_${s.name}(int can_log_level, int log_level, FILE* fd, const char* prefix, const ${s.name} *in_info)
{
    if (can_log_level < log_level) {
        return;
    }

    if (!in_info)
        return;

    char next_prefix[32];
    sprintf(next_prefix, "  %s", prefix);

% for member in s.members:
    // ${member.typep} ${member.name} = ${member}
    % if member.is_handle and member.num_pointers == 0:
    VK_CMD_LOG_FD(fd, "%s.${member.name}: ${member.typep} (handle) = %p", prefix, in_info->${member.name});
    % elif member.name == 'pNext':
    // Skipping pNext
    % elif member.name == 'sType':
    // Skipping sType
    % elif member.type in blacklisted_vk_types:
    // Skipping blacklisted type
    % elif '[' in member.text and ']' in member.text and member.type == "char":
    VK_CMD_LOG_FD(fd, "%s.${member.name}: ${member.typep} = '%s'", prefix, in_info->${member.name});
    % elif '[' in member.text and ']' in member.text and not member.array_count_member and not member.name == "memoryTypeBits":
    // Skipping array type
    VK_CMD_LOG_FD(fd, "%s.${member.name}[...]: ${member.type} = '%p'", prefix, in_info->${member.name});
    % elif member.num_pointers > 0 or member.array_count_member:
        % if member.array_count_member and member.array_count_member == 'null-terminated': ## CStr
    VK_CMD_LOG_FD(fd, "%s.${member.name}: ${member.typep} = '%s'", prefix, in_info->${member.name});
        % elif member.array_count_member and ',null-terminated' in member.array_count_member: ## CStr[]
    int count_${member.name} = in_info->${member.array_count_member.split(',')[0]};
    if (in_info->${member.name}) {
        for (uint32_t i = 0; i < count_${member.name}; i++) {
            if (in_info->${member.name}[i]) {
                VK_CMD_LOG_FD(fd, "%s.${member.name}[%d]: ${member.type}* = '%s'", prefix, i, in_info->${member.name}[i]);
            }
        }
    }
        % elif member.array_count_member and "latexmath" not in member.array_count_member: ## Array
    int count_${member.name} = in_info->${member.array_count_member};
    if (in_info->${member.name}) {
            % if member.type == 'void':
        VK_CMD_LOG_FD(fd, "%s.${member.name}: ${member.typep} = 0x%lx", prefix, (int64_t)(in_info->${member.name}));
            % elif member.num_pointers > 1:
        VK_CMD_LOG_FD(fd, "%s.${member.name}: ${member.typep} = 0x%lx", prefix, (int64_t)(in_info->${member.name}));
            % else:
        for (uint32_t i = 0; i < count_${member.name}; i++) {
                % if member.is_handle and get_wrapper_type_for_vk_type(member.type):
            VK_CMD_LOG_FD(fd, "%s.${member.name}[%d]: ${member.typep} (handle) = %lx", prefix, i, (int64_t) in_info->${member.name}[i]);
                % elif member.resolved_type in all_vk_types:
                    % if member.num_pointers == 2:
            #error "Not implemented ${member.text}"
                    % else:
            // Type[i] = ${member.text}
            VK_CMD_LOG_FD(fd, "%s.${member.name}[%d]: ${member.typep}", prefix, i);
            vk_print_${member.type}(can_log_level, log_level, fd, next_prefix, &in_info->${member.name}[i]);
                    % endif
                % else:
            VK_CMD_LOG_FD(fd, "%s.${member.name}[%d]: ${member.typep} = 0x%lx", prefix, i, (int64_t)(in_info->${member.name}[i]));
                % endif
        }
            % endif
    }
        % elif member.is_handle:
    VK_CMD_LOG_FD(fd, "%s.${member.name}: ${member.typep} (handle) = %p", prefix, in_info->${member.name});
        % elif member.resolved_type in all_vk_types:
    if (in_info->${member.name}) {
        VK_CMD_LOG_FD(fd, "%s.${member.name}: ${member.typep}", prefix);
        vk_print_${member.type}(can_log_level, log_level, fd, next_prefix, in_info->${member.name});
    }
        % else:
    // Other types
    VK_CMD_LOG_FD(fd, "%s.${member.name}: ${member.typep} = %p", prefix, in_info->${member.name});
        % endif
    % elif member.resolved_type in all_vk_types: ## Struct types
    VK_CMD_LOG_FD(fd, "%s.${member.name}: ${member.typep}", prefix);
    vk_print_${member.type}(can_log_level, log_level, fd, next_prefix, &in_info->${member.name}); // Structs ${member}
    % elif member.num_pointers == 0 and member.type not in blacklisted_vk_types: ## Non-ptr types
    VK_CMD_LOG_FD(fd, "%s.${member.name}: ${member.typep} = 0x%lx", prefix, (int64_t)(in_info->${member.name})); // Non-ptr types
    % endif
% endfor
% if s.name in pnext_map:
    // Has pNexts: ${pnext_map[s.name]}
    if (in_info->pNext) {
        vk_foreach_struct_const(pnext, in_info->pNext) {
            switch ((int32_t)pnext->sType) {
    % for ext_name in pnext_map[s.name]:
            // "${s.name}: pNext extension ${ext_name}"
            case ${ext_name.sType}:
                VK_CMD_LOG_FD(fd, "%s.pNext(${ext_name})", prefix);
                vk_print_${ext_name}(can_log_level, log_level, fd, next_prefix, (const ${ext_name} *)pnext);
                break;
    % endfor
            default:
                VK_CMD_LOG_FD(fd, "%s.pNext(UNKNOWN %s / %d)", prefix, vk_StructureType_to_str(pnext->sType), pnext->sType);
                break;
            }
        }
    }
% endif

#ifdef PRINTER_EXTRAS_${s.name}
    PRINTER_EXTRAS_${s.name}
#endif
}


% endif
% endfor
