// Copyright © 2025 Lee Gao
// SPDX-License-Identifier: MIT

// DO NOT EDIT - This file is automatically generated by vk_unwrapper_gen.py

#include "vk_unwrappers.h"
#include "vulkan/runtime/vk_log.h"
#include "vulkan/util/vk_util.h"

#define __VK_ALLOC(type) __VK_ALLOC2(type, sizeof(type))
#define __VK_ALLOC2(type, size) ({ \
    type* __output = device ? \
    ((type *) vk_zalloc(&device->vk.alloc, size, alignof(type), VK_SYSTEM_ALLOCATION_SCOPE_OBJECT)) : \
    ((type *) malloc(size)); \
    if (__output) { \
        struct temp_object_node *node = device ? \
            vk_alloc(&device->vk.alloc, sizeof(struct temp_object_node), 8, VK_SYSTEM_ALLOCATION_SCOPE_OBJECT) \
            : malloc(sizeof(struct temp_object_node)); \
        node->ptr = __output; \
        node->device = device; \
        list_addtail(&node->link, &temp->objects); \
    } \
    __output; \
})

/*
    Inductive logic for unwrapping objects (if tainted):
        handle_X x: unwrap_handle_X(x) if tainted(x) else x
        int x: x
        VkX(A a, B b, C c, ...) x: VkX(unwrap_A(a), unwrap_B(b), unwrap_C(c), ...) if tainted(a, b, c, ...) else x

        handle_X* x: alloc(unwrap(*x)) if tainted(*x) else x
        int* x: x
        VkX(A a, ...)* x: alloc(unwrap(*x)) if tainted(a, b, c, ...) else x
        void* x: x

        handle_X[n] x: list(n, unwrap_handle_X(x[i])) if tainted(x) else x
        int[n] x: x
        VkX(A a, ...)[n] x: list(n, VkX(unwrap_A(x[i]->a), ...)) if tainted(a, b, c, ...) else x
        void[n] x: x
        cstr[n] x: x

        handle_X** x: error if tainted(x) else x
        int** x: x
        VkX(A a, ...)** x: error if tainted(x) else x
        void** x: x
        cstr[n]* x: x

    Tainted: ${sorted(list(tainted))}
*/

% for s in structs:
<%
    # Helper to generate unwrapping code for a handle
    def unwrap_handle(member):
        wrapper_type = get_wrapper_type_for_vk_type(member.type)
        if not wrapper_type:
            # Not a wrapped handle, just copy.
            return f"// out_info->{member.name} = in_info->{member.name}; // not wrapped"

        handle_cast = f"{wrapper_type}_from_handle"
        return f"""
   if (in_info->{member.name} != VK_NULL_HANDLE) {{
      VK_FROM_HANDLE({wrapper_type}, wrapper_obj, in_info->{member.name});
      out_info->{member.name} = wrapper_obj->dispatch_handle;
   }} else {{
      out_info->{member.name} = VK_NULL_HANDLE;
   }}
"""
    #enddef
%>
<%def name="_unwrap_handle(member)">
% if not get_wrapper_type_for_vk_type(member.type):
    // Passthrough - handle not wrapped
% elif member.num_pointers == 0:
    if (in_info->${member.name} != VK_NULL_HANDLE) {
        VK_FROM_HANDLE(${get_wrapper_type_for_vk_type(member.type)}, obj, in_info->${member.name});
        out_info->${member.name} = obj->dispatch_handle;
    }
% elif member.array_count_member:
    if (in_info->${member.name}) {
        out_info->${member.name} = __VK_ALLOC2(${member.type}, in_info->${member.array_count_member} * sizeof(${member.type}));
        for (uint32_t i = 0; i < in_info->${member.array_count_member}; i++) {
            VK_FROM_HANDLE(${get_wrapper_type_for_vk_type(member.type)}, wrapper_obj, in_info->${member.name}[i]);
            ((${member.type} *) out_info->${member.name})[i] = wrapper_obj ? wrapper_obj->dispatch_handle : VK_NULL_HANDLE;
        }
    }
% elif member.num_pointers == 1:
    if (in_info->${member.name}) {
        if (*in_info->${member.name} != VK_NULL_HANDLE) {
            out_info->${member.name} = __VK_ALLOC2(${member.type}, sizeof(${member.type}));
            VK_FROM_HANDLE(${get_wrapper_type_for_vk_type(member.type)}, obj, *in_info->${member.name});
            *out_info->${member.name} = obj->dispatch_handle;
        }
    }
% elif member.num_pointers == 2:
    #error "Not implemented: ${member.typep} with 2 pointers"
% else:
    #error "Not implemented: ${member.typep}"
% endif
</%def>
<%def name="_unwrap_struct(member)">
% if member.num_pointers == 0:
    unwrap_${member.type}(device, &out_info->${member.name}, &in_info->${member.name});
% elif member.array_count_member:
    if (in_info->${member.name}) {
        out_info->${member.name} = __VK_ALLOC2(${member.type}, in_info->${member.array_count_member} * sizeof(${member.type}));
        for (uint32_t i = 0; i < in_info->${member.array_count_member}; i++) {
            unwrap_${member.type}(
                temp,
                device, 
                &(((${member.typep})out_info->${member.name})[i]), 
                &(((const ${member.typep})in_info->${member.name})[i]));
        }
    }
% elif member.num_pointers == 1:
    if (in_info->${member.name}) {
        out_info->${member.name} = __VK_ALLOC(${member.type});
        unwrap_${member.type}(temp, device, (${member.type}*) out_info->${member.name}, in_info->${member.name});
    }
% elif member.num_pointers == 2:
    #error "Not implemented: ${member.typep} with 2 pointers"
% else:
    #error "Not implemented: ${member.typep}"
% endif
</%def>
<%def name="_unwrap_special(device, member)">
% if member.num_pointers == 0:
    out_info->${member.name} = ${special_types[member.type]}(device, in_info->${member.name});
% elif member.array_count_member:
    if (in_info->${member.name}) {
        out_info->${member.name} = __VK_ALLOC2(${member.type}, in_info->${member.array_count_member} * sizeof(${member.type}));
        for (uint32_t i = 0; i < in_info->${member.array_count_member}; i++) {
            ((${member.typep})out_info->${member.name})[i] = ${special_types[member.type]}(device, in_info->${member.name}[i]);
        }
    }
% elif member.num_pointers == 1:
    if (in_info->${member.name}) {
        out_info->${member.name} = __VK_ALLOC(${member.type});
        *((${member.typep})out_info->${member.name}) = ${special_types[member.type]}(device, in_info->${member.name});
    }
% elif member.num_pointers == 2:
    #error "Not implemented: ${member.typep} with 2 pointers"
% else:
    #error "Not implemented: ${member.typep}"
% endif
</%def>
% if s.name not in tainted:
// ${s.name} - Not tainted, unwrapping is just a copy
% endif
void
unwrap_${s.name}_members_only(struct temporary_objects* temp, struct wrapper_device *device,
                          ${s.name} *out_info,
                          const ${s.name} *in_info)
{
    if (!in_info)
        return;

    *out_info = *in_info;

% for member in s.members:
    // ${member.typep} ${member.name} = ${member}
% if member.type not in tainted:
<% continue %>
% else:
    //   Uses these types that must be unwrapped: ${tainted[member.type]}
% endif
% if member.name == 'pNext' or member.name == 'sType':
<% continue %>
% endif
% if member.is_handle:
${_unwrap_handle(member)}
% elif member.is_struct or member.is_union:
${_unwrap_struct(member)}
% elif member.type in special_types:
${_unwrap_special(device, member)}
% elif member.num_pointers == 0:
    // Passthrough - primitives
% elif member.array_count_member == 'null-terminated':
    // Passthrough - null-terminated cstr
% elif member.array_count_member and member.type == 'void':
    // Passthrough - ${member.typep}
% else:
    #error "Unhandled member type: ${member.typep} for ${s.name}.${member.name}"
% endif
% endfor
}

void unwrap_${s.name}(struct temporary_objects* temp, struct wrapper_device *device,
                          ${s.name} *out_info,
                          const ${s.name} *in_info)
{
    if (!in_info)
        return;

    unwrap_${s.name}_members_only(temp, device, out_info, in_info);
    ##// Invariant: out_pnext_ptr points to the current output pnext
    ##VkBaseOutStructure **out_pnext_ptr = (VkBaseOutStructure **)&out_info->pNext;
    ##vk_foreach_struct_const(pnext, in_info->pNext) {
        ##switch ((int32_t)pnext->sType) {
    // TODO: Fix potentially unknown pNext structs (don't lose anything here)
    /*
% if s.name in pnext_map:
    // Has pNexts: ${pnext_map[s.name]}
    struct VkBaseOutStructure *head = NULL, *tail = NULL;
    vk_foreach_struct_const(item, in_info->pNext) {
        size_t item_size = vk_structure_type_size(item);
        WLOGE("${s.name} pnext: sType = %d, size = %d", item->sType, item_size);
        if (item_size == 0) {
            // Invalid structure, skip it.
            WLOGE("Invalid structure in pNext (%d) chain: %p", item->sType, item);
            continue;
        }


        struct VkBaseOutStructure *new_item = __VK_ALLOC2(VkBaseOutStructure, item_size);
        memcpy(new_item, item, item_size);

        switch ((int32_t)item->sType) {
    % for ext_name in pnext_map[s.name]:
        % if ext_name.name not in tainted:
<% continue %>
        % endif
        // "${s.name}: pNext extension ${ext_name} contains a wrapped handle (${tainted[ext_name.name]}) and must be unwrapped"
        case ${ext_name.sType}:
            unwrap_${ext_name}_members_only(temp, device, (${ext_name} *)new_item, (const ${ext_name} *)item);
            break;
    % endfor
        default:
            break;
        }


        if (!head)
            head = new_item;
        if (tail)
            tail->pNext = new_item;
        tail = new_item;
    }

    out_info->pNext = head;

% endif
    */
        ##default:
        ##    /* The calculate function allocated space, now we copy it. */
        ##    memcpy(*out_pnext_ptr, pnext, vk_structure_type_size(pnext));
        ##    break;
        ##}
        ##out_pnext_ptr = &(*out_pnext_ptr)->pNext;
    ##}
    ##*out_pnext_ptr = NULL;
}

% endfor
