## Copyright © 2024 The Mesa3D Authors
## SPDX-License-Identifier: MIT

## DO NOT EDIT - This file is automatically generated by vk_unwrapper_gen.py

#ifndef VK_UNWRAPPER_H
#define VK_UNWRAPPER_H

#include "wrapper_private.h"
#include "vulkan/util/vk_alloc.h"

#ifdef __cplusplus
extern "C" {
#endif

struct temporary_objects {
    struct list_head objects;
};

struct temp_object_node {
    struct list_head link;
    void *ptr;
    struct wrapper_device *device;
};

static void free_temp_objects(struct temporary_objects* temp) {
    // Clean up temporary descriptor pools associated with this command buffer
    if (!list_is_empty(&temp->objects)) {
        list_for_each_entry_safe(struct temp_object_node, node, &temp->objects, link) {
            if (node->device) {
                vk_free(&node->device->vk.alloc, node->ptr);
                list_del(&node->link);
                vk_free(&node->device->vk.alloc, node);
            } else {
                free(node->ptr);
                list_del(&node->link);
                free(node);
            }
        }
    }
}

% for s in structs:

void
unwrap_${s.name}_members_only(struct temporary_objects*, struct wrapper_device *device,
                          ${s.name} *out_info,
                          const ${s.name} *in_info);

void
unwrap_${s.name}(struct temporary_objects*, struct wrapper_device *device,
                          ${s.name} *out_info,
                          const ${s.name} *in_info);

% endfor

##% for s in wrapped_handles:
###define NEEDS_UNWRAPPING_${s}
##% endfor
% for s, struct_, uses in needs_unwrapping:
// uses = ${uses}
#define NEEDS_UNWRAPPING_${s}
% endfor

#ifdef __cplusplus
}
#endif

#endif /* VK_UNWRAPPER_H */